---

- name: Install Docker
  yum:
    name: docker
    state: present
  become: yes

- name: Start Docker
  service: name=docker state=started enabled=yes

- name: Install Docker Compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.19.0/docker-compose-Linux-x86_64"
    dest: "/usr/bin/docker-compose"
    force: True
    owner: "root"
    group: "root"
    mode: "0755"