--- 

- name: Download jdk
  get_url:
    url: "http://download.oracle.com/otn-pub/java/jdk/9.0.4+11/c2514751926b4512b076cc82f959763f/jdk-9.0.4_linux-x64_bin.rpm"
    dest: /tmp/jdk.rpm
    headers: "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie"

- name: Install jdk
  yum:
    name: /tmp/jdk.rpm
    state: present
  become: yes
  